window.map = '' +
'MMMMMMMMM......\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMMMMMMMMMM\n'+
'MMMMMMM........\n'+
'MMMMMMM........\n'+
'MMMMMMM........\n'+
'MMMMMMM........\n'+
'MMMMMMM........\n'+
'MMMMMMM........\n';
